version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webmodern-seo-dashboard
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.local
